apiVersion: v1
kind: ServiceAccount
metadata:
  name: sampleapp-pipeline-account
  namespace: tekton-pipelines
secrets:
- name: reg-cred
- name: ssh-readonly-creds-secret
- name: ssh-write-creds-secret
---

apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  namespace: tekton-pipelines
  annotations:
    kubernetes.io/service-account.name: sampleapp-pipeline-account
type: kubernetes.io/service-account-token

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sampleapp-pipeline-role
  namespace: tekton-pipelines
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sampleapp-pipeline-role-binding
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sampleapp-pipeline-role
subjects:
- kind: ServiceAccount
  name: sampleapp-pipeline-account