apiVersion: v1
kind: Secret
metadata:
  name: ssh-readonly-creds-secret
  namespace: tekton-pipelines
data:
  id_rsa: <base64-top-secret>
  known_hosts: <base64-top-secret>
  config: <base64-top-secret>
---

apiVersion: v1
kind: Secret
metadata:
  name: ssh-write-creds-secret
  namespace: tekton-pipelines
data:
  id_rsa: <base64-top-secret>
  known_hosts: <base64-top-secret>
  config: <base64-top-secret>
---

apiVersion: v1
kind: Secret
metadata:
  name: reg-cred
  namespace: tekton-pipelines
data:
  config.json: <base64-top-secret>
---

apiVersion: v1
kind: Secret
metadata:
  name: sonar-settings-secret
  namespace: tekton-pipelines
data:
  sonar-project.properties: <base64-top-secret>