apiVersion: v1
kind: Secret
metadata:
  name: ssh-readonly-creds-secret
  namespace: tekton-pipelines
data:
  id_rsa: <top-secret>
  known_hosts: <top-secret>
  config: <top-secret>
---

apiVersion: v1
kind: Secret
metadata:
  name: ssh-write-creds-secret
  namespace: tekton-pipelines
data:
  id_rsa: <top-secret>
  known_hosts: <top-secret>
  config: <top-secret>
---

apiVersion: v1
kind: Secret
metadata:
  name: reg-cred
  namespace: tekton-pipelines
data:
  config.json: <top-secret>
---

apiVersion: v1
kind: Secret
metadata:
  name: sonar-settings-secret
  namespace: tekton-pipelines
data:
  sonar-project.properties: c29uYXIucHJvamVjdEtleT1leGFtcGxlLWFwcApzb25hci5wcm9qZWN0VmVyc2lvbj0xLjAKc29uYXIuc291cmNlRW5jb2Rpbmc9VVRGLTgKc29uYXIuaG9zdC51cmw9aHR0cHM6Ly9zb25hci5sb2NhbApzb25hci5zb3VyY2VzPXBhdGgtdG8tc291cmNlLWNvZGUKc29uYXIudmlzdWFsc3R1ZGlvLmVuYWJsZT10cnVlCnNvbmFyLmxvZ2luPWV4YW1wbGUKc29uYXIucGFzc3dvcmQ9ZXhhbXBsZQo=