apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-api-pipelinerun-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: sampleapp-api-pipeline
  params:
    - name: gitUrl
      value: git@bitbucket.org:username/sampleapp-api.git
    - name: infraGitUrl
      value: git@bitbucket.org:username/sampleapp-infra.git
    - name: branchName
      value: master
    - name: infraBranchName
      value: master
    - name: imageUrl
      value: example.com/sampleapp/api
    - name: imageTag
      value: v0.0.1
    - name: pathToContext
      value: './src'
    - name: sonar-url
      value: https://sonar.local
    - name: sonar-project-name
      value: example-app
  serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
    - name: git-infra-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 100Mi
    - name: ssh-creds
      secret:
        secretName: ssh-readonly-creds-secret
    - name: ssh-write-creds
      secret:
        secretName: ssh-write-creds-secret
    - name: dockerconfig
      secret:
        secretName: reg-cred
    - name: sonar-settings
      secret:
        secretName: sonar-settings-secret